- hosts: database
  become: true
  roles:
    - role: postgresql
      vars:
         postgresql_version: "14"
         postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
         postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
         ansible_ssh_pipelining: true
